### ISSUE TITLE
Add https://searx.zimro.xyz

### ISSUE THREAD

**Issue by ziimro** [searxng/searx-instances#217]
### Requirements

- [X] It is my instance.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

+ Increased timeout range for `wikidata` from 3.0 to 5.0 since it kept returning timeout
+ Disabled flickr images by default and enabled `use_mobile_ui` for google

Im running prometheus with grafana on my server just to check up on Mem/Traffic usage

**Comment by ononoki1** [comment]
Hi! Your HSTS header `max-age=63072000;includeSubDomains; preload, max-age=63072000` is not valid. As a result, your [CSP](https://observatory.mozilla.org/analyze/searx.zimro.xyz) grade is not optimal. A valid one is like `max-age=63072000; includeSubDomains; preload`.

**Comment by ziimro** [comment]
> Hi! Your HSTS header `max-age=63072000;includeSubDomains; preload, max-age=63072000` is not valid. As a result, your [CSP](https://observatory.mozilla.org/analyze/searx.zimro.xyz) grade is not optimal. A valid one is like `max-age=63072000; includeSubDomains; preload`.

my headers for `Strict-Transport-Security` are just `add_header Strict-Transport-Security "max-age=63072000" always;` what should i change it to?
Heres a full list of my settings for `/` in nginx
```
add_header  Content-Security-Policy "upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self' https://github.com/searxng/searxng/issues/new; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com" always;
add_header Permissions-Policy "accelerometer=(),ambient-light-sensor=(),autoplay=(),camera=(),encrypted-media=(),focus-without-user-activation=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(),midi=(),payment=(),picture-in-picture=(),speaker=(),sync-xhr=(),usb=(),vr=()" always;
add_header  Feature-Policy "accelerometer 'none';ambient-light-sensor 'none'; autoplay 'none';camera 'none';encrypted-media 'none';focus-without-user-activation 'none'; geolocation 'none';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'none';picture-in-picture 'none'; speaker 'none';sync-xhr 'none';usb 'none';vr 'none'" always;
add_header X-Robots-Tag "noindex, noarchive, nofollow" always;
add_header Referrer-Policy "no-referrer" always;
add_header Cache-Control "no-cache, no-store" always;
add_header Pragma "no-cache" always;
add_header X-Frame-Options SAMEORIGIN always;
add_header Strict-Transport-Security "max-age=63072000" always;
```

**Comment by ononoki1** [comment]
You add `max-age=63072000;includeSubDomains; preload` in somewhere else. Can you show the whole config of this `server` block?

**Comment by ziimro** [comment]
`/stats/errors`
```
add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
add_header Access-Control-Allow-Origin  "*" always;
```
`/stats/checker`
```
add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
add_header Access-Control-Allow-Origin  "*" always;
```
`/image_proxy`
```
add_header Content-Security-Policy "default-src 'none'; img-src 'self' data:" always;
```
I use nginx-proxy-manager to manage my websites, i have the `cache assets = false`, `block common exploits = true` and `websockets support = true`

**Comment by ziimro** [comment]
> You add `max-age=63072000;includeSubDomains; preload` in somewhere else. Can you show the whole config of this `server` block?

in `settings.yml` i have those options in my `server:` block
```yml
server:
  # If you change port, bind_address or base_url don't forget to rebuild
  # instance's environment (make buildenv)
  port: 8080
  bind_address: "127.0.0.1"
  base_url: false  # Possible values: false or "https://example.org/location".
  limiter: true  # rate limit the number of request on the instance, block some bots

  # If your instance owns a /etc/searxng/settings.yml file, then set the following
  # values there.

  secret_key: "super_secret_indeed"  # change this!
  # Proxying image results through searx
  image_proxy: true
  # 1.0 and 1.1 are supported
  http_protocol_version: "1.0"
  # POST queries are more secure as they don't show up in history but may cause
  # problems when using Firefox containers
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer
```
