### ISSUE TITLE
Add https://searx.headpat.exchange

### ISSUE THREAD

**Issue by y0nei** [searxng/searx-instances#391]
### Requirements (make sure to read all of them)

- [X] It is my instance. I bought the domain myself and I own this domain. Free domains (e.g. Freenom) and shared domains (e.g. noip.com) are not allowed.
- [X] I give the right to `check.searx.space` to check my instance (every 3 hours for the response times, every 24 hours for the other tests).
- [X] I acknowledge that managing a public instance is not an easy task and require spending time to keep the instance in good health. E.g. look after your instance by using a monitoring system.
- [X] I guarantee to keep an uptime per month of my instance at **minimum 90%**. Please ask for a removal of your instance if there is a planned long downtime or notify us [here](https://github.com/searxng/searx-instances/discussions/categories/report-instance-downtime) for a short downtime.
- [X] I do not track the users of my instance with any analytics or tracking software.
- [X] I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)
- [X] I control the final webserver (software) that is serving the requests to the users of my instance. Here is a non-exhaustive list of forbidden hosting types: Cloudflare, PaaS, managed (hosting provider controlled) HTTP(S) load balancer (e.g. AWS ALB), shared Web hosting. TCP load balancer is fine. Cloudflare DNS only (grey cloud) is fine.
- [X] If needed, I can restrict users from accessing my instance for the only sole reason of keeping my instance in working conditions for the other users ([detailed description](https://github.com/searxng/searx-instances/pull/346) - evidence need to be provided when asked). Other means of restriction is forbidden.

### Bot protection

Yes, I have enabled the limiter plugin built in SearXNG.

### Comment

No much to say, here is the [Mozilla Observatory grade](https://observatory.mozilla.org/analyze/searx.headpat.exchange) and the [status dashboard](https://status.headpat.exchange/) of my services, searxng uptime has been added there.

**Comment by ononoki1** [comment]
Hi @y0nei, your [TLS](https://cryptcheck.fr/https/searx.headpat.exchange) grade is **F**. You must at least get an **E** grade for your instance to be added.

**Comment by y0nei** [comment]
> Hi @y0nei, your [TLS](https://cryptcheck.fr/https/searx.headpat.exchange) grade is **F**. You must at least get an **E** grade for your instance to be added.

Havent worked much with TLS options, should i just dissalow the cipher suites that show up in red? `AES` and `DES` ones?

**Comment by y0nei** [comment]
Okay, i have modified the available suites to this: (traefik configuration)
```
tls:
  options:
    default:
      minVersion: VersionTLS12
      # - TLS_RSA_WITH_AES_128_GCM_SHA256
      # - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
      # - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_RSA_WITH_RC4_128_SHA
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
```
The website seems to disallow me to further run TLS checks for my domain but i have removed the problematic `ECDHE-RSA-RC4-SHA` cipher it highlights as red
